import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Données mises à jour avec groupes musculaires multiples
const defaultMachines = [
    // Exercices pour les épaules
    { nom: 'Russian twist avec développé épaules', description: 'Exercice ciblant les deltoïdes antérieurs et latéraux', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Développé militaire', description: 'Développé avec barre pour épaules', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Développé Arnold', description: 'Variante du développé avec rotation', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Face pull', description: 'Tirage vers le visage avec poulie', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Élévations latérales à la poulie', description: 'Mouvement d\'abduction avec poulie', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Élévations latérales avec haltères', description: 'Mouvement d\'abduction avec haltères', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Développé épaules avec haltères', description: 'Développé avec haltères pour épaules', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Presse à épaules inclinée', description: 'Développé sur machine inclinée', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Élévations frontales', description: 'Élévation des bras vers l\'avant', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Tirage menton avec haltères', description: 'Tirage vertical vers le menton', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Oiseau avec haltères', description: 'Travail des deltoïdes postérieurs', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Rotation externe de l\'épaule avec haltère', description: 'Exercice de stabilisation', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Pompes piquées', description: 'Variante des pompes sur un banc', groupe: 'Épaules, Pectoraux', categorie: 'libre' },
    { nom: 'Tirage menton avec barre guidée', description: 'Tirage vertical guidé', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Élévations latérales avec landmine', description: 'Utilise une fixation pour barre', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Handstand push-up', description: 'Pompes en équilibre', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Tirage menton avec élastique', description: 'Tirage vertical avec résistance élastique', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Oiseau avec élastique', description: 'Travail des deltoïdes postérieurs avec élastique', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Développé épaules avec élastique', description: 'Développé avec résistance élastique', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Thruster avec kettlebell', description: 'Mouvement combiné squat et développé', groupe: 'Épaules, Jambes', categorie: 'libre' },
    { nom: 'Développé épaule unilatéral avec kettlebell', description: 'Travail d\'un seul côté', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Développé épaule unilatéral avec élastique', description: 'Travail unilatéral avec élastique', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Élévations latérales inclinées avec haltères', description: 'Variante sur banc incliné', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Rotation externe de l\'épaule couché avec haltère', description: 'Exercice couché pour coiffe des rotateurs', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Croix de fer avec haltères', description: 'Bras en croix avec résistance', groupe: 'Épaules', categorie: 'libre' },
    { nom: 'Extension horizontale des épaules avec élastique', description: 'Mouvement d\'extension horizontale', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Développé épaules à la machine', description: 'Développé sur machine guidée', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Développé épaules debout à la Smith machine', description: 'Développé guidé en position debout', groupe: 'Épaules', categorie: 'guidee' },
    { nom: 'Développé épaules assis avec élastique', description: 'Variation assise avec élastique', groupe: 'Épaules', categorie: 'fonctionnel' },
    { nom: 'Oiseau inversé avec sangles de suspension', description: 'Utilisation de sangles TRX', groupe: 'Épaules, Dos', categorie: 'fonctionnel' },

    // Exercices pour les biceps (d'après les captures d'écran)
    { nom: 'Curl à la barre', description: 'Flexion du coude avec barre', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl concentré', description: 'Curl avec concentration sur un seul bras', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl pupitre barre EZ', description: 'Curl avec barre coudée et support', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl allongé à la poulie', description: 'Curl en position allongée', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Curl poulie en position squat', description: 'Curl avec position de jambes fléchies', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Curl au pupitre à la poulie', description: 'Curl avec poulie et support', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Curl biceps assis à la machine', description: 'Curl sur machine guidée', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Curl haltère debout sur banc incliné', description: 'Curl avec support incliné', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl Spider', description: 'Variante avec bras sur plan incliné', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl haltère incliné avec rotation', description: 'Curl avec supination accentuée', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl biceps à la poulie basse', description: 'Curl depuis poulie en position basse', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Traction supination', description: 'Traction avec prise en supination', groupe: 'Biceps, Dos', categorie: 'libre' },
    { nom: 'Curl Zottman', description: 'Curl avec rotation en phase négative', groupe: 'Biceps, Avant-bras', categorie: 'libre' },
    { nom: 'Curl en prise marteau avec élastique', description: 'Curl avec prise neutre et élastique', groupe: 'Biceps', categorie: 'fonctionnel' },
    { nom: 'Curl à la poulie vis-à-vis', description: 'Curl face à face avec poulies', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Drag curl avec haltères', description: 'Curl avec mouvement vertical des coudes', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl inversé à la barre', description: 'Curl avec prise pronation', groupe: 'Biceps, Avant-bras', categorie: 'libre' },
    { nom: 'Curl haltères prise neutre', description: 'Curl avec prise marteau', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Drag curl à la Smith machine', description: 'Drag curl avec barre guidée', groupe: 'Biceps', categorie: 'guidee' },
    { nom: 'Drag curl', description: 'Curl avec coudes vers l\'arrière', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl biceps alterné avec haltères', description: 'Curl en alternant les bras', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Waiter curl', description: 'Curl avec haltère tenu verticalement', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl biceps alterné en supination sur banc incliné', description: 'Curl alterné avec banc', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl biceps avec élastique', description: 'Curl utilisant résistance élastique', groupe: 'Biceps', categorie: 'fonctionnel' },
    { nom: 'Curl unilatéral avec sangles de suspension', description: 'Curl avec TRX pour un bras', groupe: 'Biceps', categorie: 'fonctionnel' },
    { nom: 'Curl haltère prise marteau au pupitre', description: 'Curl neutre avec support', groupe: 'Biceps', categorie: 'libre' },
    { nom: 'Curl avec sangles de suspension', description: 'Curl avec TRX', groupe: 'Biceps', categorie: 'fonctionnel' },
    { nom: 'Curl incliné à la poulie', description: 'Curl avec poulie et banc incliné', groupe: 'Biceps', categorie: 'guidee' },

    // Exercices pour les triceps (d'après les captures d'écran)
    { nom: 'Barre front', description: 'Extension avec barre au-dessus de la tête', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Dips aux barres parallèles', description: 'Flexion et extension sur barres', groupe: 'Triceps, Pectoraux', categorie: 'libre' },
    { nom: 'Extensions verticales d\'un bras avec haltère', description: 'Extension unilatérale', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extension verticale assis à la barre', description: 'Extension avec barre en position assise', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps à la machine Technogym', description: 'Extension sur machine guidée', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Dips sur une chaise', description: 'Dips avec support de chaise', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps incliné à la poulie basse', description: 'Extension avec inclinaison', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Pompes', description: 'Pompes classiques', groupe: 'Triceps, Pectoraux', categorie: 'libre' },
    { nom: 'Extensions concentrées des triceps à la poulie', description: 'Extension ciblée avec poulie', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Extension horizontale à la poulie', description: 'Extension en position horizontale', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Extension verticale à la poulie basse', description: 'Extension depuis poulie basse', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Extensions verticales à la poulie haute', description: 'Extension depuis poulie haute', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Dips assis à la machine Matrix', description: 'Dips guidés assis', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Kickback alterné assis', description: 'Kickback en alternant les bras', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps incliné avec haltères', description: 'Extension avec support incliné', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps décliné avec haltères', description: 'Extension avec support décliné', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Handstand pushup', description: 'Pompes en appui renversé', groupe: 'Triceps, Épaules', categorie: 'libre' },
    { nom: 'Dips assistés à la machine', description: 'Dips avec assistance', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Dips assis à la machine Hammer Strength', description: 'Dips guidés sur machine spécifique', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Kickback debout avec haltères', description: 'Extension arrière en position debout', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps assis avec haltère', description: 'Extension en position assise', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps couché avec haltères', description: 'Extension en position couchée', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions des triceps incliné à la Smith machine', description: 'Extension sur machine guidée inclinée', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Développé couché prise serrée à la Smith machine', description: 'Développé avec mains rapprochées', groupe: 'Triceps, Pectoraux', categorie: 'guidee' },
    { nom: 'Extensions des triceps à la poulie haute à la corde', description: 'Extension avec accessoire corde', groupe: 'Triceps', categorie: 'guidee' },
    { nom: 'Extensions des triceps avec sangles de suspension', description: 'Extension avec TRX', groupe: 'Triceps', categorie: 'fonctionnel' },
    { nom: 'Dips aux anneaux', description: 'Dips sur anneaux de gymnastique', groupe: 'Triceps, Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Dips sur banc', description: 'Dips avec support de banc', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Kickback', description: 'Extension arrière classique', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Dips entre deux bancs', description: 'Dips avec deux supports', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extensions verticales à deux mains avec haltère', description: 'Extension avec haltère tenu à deux mains', groupe: 'Triceps', categorie: 'libre' },
    { nom: 'Extension des triceps au-dessus de la tête avec élastique', description: 'Extension avec résistance élastique', groupe: 'Triceps', categorie: 'fonctionnel' },
    { nom: 'Extension verticale des triceps avec élastique', description: 'Extension verticale avec élastique', groupe: 'Triceps', categorie: 'fonctionnel' },
    { nom: 'Tate press à un bras avec haltère', description: 'Extension spécifique pour triceps', groupe: 'Triceps', categorie: 'libre' },

    // Exercices pour les pectoraux (d'après les captures d'écran)
    { nom: 'Pompes inclinées sur Smith Machine', description: 'Pompes avec support incliné', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Pompes inclinées avec sangles de suspension', description: 'Pompes avec TRX', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Développé couché', description: 'Mouvement de base pour pectoraux', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé incliné à la barre', description: 'Développé sur banc incliné', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés couché avec haltères', description: 'Écartés classiques', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés à la poulie vis-à-vis', description: 'Écartés avec poulies face à face', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Développé incliné à la machine convergente', description: 'Développé sur machine guidée', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Développé décliné à la barre', description: 'Développé sur banc décliné', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés décliné avec haltères', description: 'Écartés sur banc décliné', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés Hyght', description: 'Variante d\'écartés', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé couché prise inversée', description: 'Développé avec prise en pronation', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés unilatéraux à la landmine', description: 'Écartés avec fixation pour barre', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Pompes', description: 'Pompes classiques', groupe: 'Pectoraux, Triceps', categorie: 'libre' },
    { nom: 'Développé couché avec chaînes', description: 'Développé avec résistance variable', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé décliné avec haltère', description: 'Développé décliné unilatéral', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Pullover avec haltère', description: 'Étirement des pectoraux avec haltère', groupe: 'Pectoraux, Dos', categorie: 'libre' },
    { nom: 'Développé couché à la Smith machine', description: 'Développé couché guidé', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Hex press à la Smith machine', description: 'Presse hexagonale guidée', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Écartés couché à la poulie vis-à-vis', description: 'Écartés à la poulie en position couchée', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Développé debout avec élastique', description: 'Développé avec résistance élastique', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Développé couché serré avec haltères', description: 'Développé avec mains rapprochées', groupe: 'Pectoraux, Triceps', categorie: 'libre' },
    { nom: 'Svend press', description: 'Presse avec poids plaqués ensemble', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé couché avec élastique', description: 'Développé avec résistance additionnelle', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés à la poulie vis à vis haute à genoux', description: 'Écartés à genoux', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Développé décliné avec élastique', description: 'Développé décliné avec résistance élastique', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Développé couché Larsen', description: 'Développé avec pieds levés', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé couché unilatéral avec kettlebell', description: 'Développé à un bras', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé couché au sol avec kettlebell', description: 'Développé sans banc', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé à la landmine à genoux pour pectoraux', description: 'Développé avec landmine', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Développé assis à la machine pour les pectoraux', description: 'Développé sur machine guidée assis', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Écartés avec sangles de suspension', description: 'Écartés avec TRX', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Chest press avec sangles de suspension', description: 'Développé avec TRX', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Écartés incliné avec haltères', description: 'Écartés sur banc incliné', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Écartés à la poulie haute', description: 'Écartés avec poulies en position haute', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Écartés avec élastique', description: 'Écartés avec résistance élastique', groupe: 'Pectoraux', categorie: 'fonctionnel' },
    { nom: 'Développé couché au sol', description: 'Développé sans banc', groupe: 'Pectoraux', categorie: 'libre' },
    { nom: 'Pec deck', description: 'Machine à papillon', groupe: 'Pectoraux', categorie: 'guidee' },
    { nom: 'Pec deck inversé', description: 'Mouvement inverse du papillon', groupe: 'Pectoraux, Dos', categorie: 'guidee' },

    // Exercices pour le dos (d'après les captures d'écran)
    { nom: 'Muscle-up', description: 'Traction suivie d\'une extension', groupe: 'Dos, Triceps', categorie: 'libre' },
    { nom: 'Traction', description: 'Traction à la barre fixe', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Tirage horizontal à la poulie', description: 'Rowing à la poulie', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Rowing barre', description: 'Rowing avec barre', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Shrug barre', description: 'Haussement d\'épaules avec barre', groupe: 'Dos, Trapèzes', categorie: 'libre' },
    { nom: 'Pull-over assis à la machine', description: 'Pull-over guidé', groupe: 'Dos, Pectoraux', categorie: 'guidee' },
    { nom: 'Traction supination', description: 'Traction avec prise en supination', groupe: 'Dos, Biceps', categorie: 'libre' },
    { nom: 'Rowing haltère à un bras', description: 'Rowing unilatéral', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Rowing « T-bar »', description: 'Rowing avec barre en T', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Tirage vertical prise serrée', description: 'Traction prise rapprochée', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Rowing en pronation assis à la machine Technogym', description: 'Rowing machine spécifique', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Extension lombaire à la machine', description: 'Extension du bas du dos', groupe: 'Dos, Lombaires', categorie: 'guidee' },
    { nom: 'Rowing à la barre en T avec machine', description: 'Rowing T-bar guidé', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Rowing en prise neutre assis à la machine', description: 'Rowing avec prise marteau', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Tirage vertical en supination à la machine Hammer Strength', description: 'Tirage vertical machine spécifique', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Soulevé de terre', description: 'Deadlift classique', groupe: 'Dos, Jambes', categorie: 'libre' },
    { nom: 'Traction assistée à la machine', description: 'Traction avec assistance', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Tractions prise neutre', description: 'Traction prise marteau', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Rowing avec haltères', description: 'Rowing avec deux haltères', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Seal row avec haltères', description: 'Rowing sur banc horizontal', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Renegade row', description: 'Rowing en position de planche', groupe: 'Dos, Abdominaux', categorie: 'libre' },
    { nom: 'Tirage vertical poitrine', description: 'Tirage devant', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Rowing unilatéral à la landmine', description: 'Rowing avec fixation pour barre', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Superman', description: 'Extension du dos en position allongée', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Rowing haltères sur banc incliné', description: 'Rowing avec support incliné', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Tractions australiennes', description: 'Tractions inversées', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Pullover avec haltère', description: 'Étirement avec haltère', groupe: 'Dos, Pectoraux', categorie: 'libre' },
    { nom: 'Shrug à la machine à mollets', description: 'Haussements d\'épaules à la machine', groupe: 'Dos, Trapèzes', categorie: 'guidee' },
    { nom: 'Bird dog', description: 'Extension bras/jambe opposés', groupe: 'Dos, Abdominaux', categorie: 'libre' },
    { nom: 'Pull-over à la poulie', description: 'Pull-over avec résistance constante', groupe: 'Dos, Pectoraux', categorie: 'guidee' },
    { nom: 'Overhead shrug', description: 'Haussements d\'épaules bras levés', groupe: 'Dos, Trapèzes', categorie: 'libre' },
    { nom: 'Pull-over décliné à la barre', description: 'Pull-over sur banc décliné', groupe: 'Dos, Pectoraux', categorie: 'libre' },
    { nom: 'Planche à barre', description: 'Maintien horizontal avec barre', groupe: 'Dos, Abdominaux', categorie: 'libre' },
    { nom: 'Shrug à la poulie', description: 'Haussements d\'épaules à la poulie', groupe: 'Dos, Trapèzes', categorie: 'guidee' },
    { nom: 'Extension lombaire au banc à 45°', description: 'Extension du bas du dos sur banc', groupe: 'Dos, Lombaires', categorie: 'libre' },
    { nom: 'Rowing buste penché avec élastique', description: 'Rowing avec élastique', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre avec machine', description: 'Deadlift guidé', groupe: 'Dos, Jambes', categorie: 'guidee' },
    { nom: 'Tractions australiennes avec sangles de suspension', description: 'Tractions inversées au TRX', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Extensions lombaires sur Swiss ball', description: 'Extension du dos sur ballon', groupe: 'Dos, Lombaires', categorie: 'fonctionnel' },
    { nom: 'Oiseau inversé avec sangles de suspension', description: 'Rowing horizontal au TRX', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Traction assistée avec élastique', description: 'Traction avec aide élastique', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Rowing avec sangles de suspension', description: 'Rowing au TRX', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Pullover avec deux haltères', description: 'Pullover avec poids séparés', groupe: 'Dos, Pectoraux', categorie: 'libre' },
    { nom: 'Rowing inversé sous une table', description: 'Rowing en position inversée', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Bent over row prise disque', description: 'Rowing avec poids disque', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Rowing unilatéral avec élastique', description: 'Rowing à un bras avec élastique', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Rowing à la Smith machine', description: 'Rowing sur machine guidée', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Tirage horizontal prise large', description: 'Rowing avec prise écartée', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Montée à la corde', description: 'Grimper de corde', groupe: 'Dos, Bras', categorie: 'fonctionnel' },
    { nom: 'Pull-over avec barre', description: 'Pull-over avec barre droite', groupe: 'Dos, Pectoraux', categorie: 'libre' },
    { nom: 'Tirage incliné à la poulie haute', description: 'Tirage en position inclinée', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Traction lestée', description: 'Traction avec poids additionnel', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Traction assistée avec banc', description: 'Traction avec aide d\'un banc', groupe: 'Dos', categorie: 'libre' },
    { nom: 'Tirage horizontal avec élastique', description: 'Rowing avec résistance élastique', groupe: 'Dos', categorie: 'fonctionnel' },
    { nom: 'Tirage vertical prise inversée', description: 'Tirage avec prise en pronation', groupe: 'Dos', categorie: 'guidee' },
    { nom: 'Tirage vertical', description: 'Mouvement de traction vers le bas', groupe: 'Dos', categorie: 'guidee' },

    // Exercices pour les quadriceps (d'après les captures d'écran)
    { nom: 'Hack squat assis', description: 'Squat sur machine en position assise', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Presse à cuisse sur le côté', description: 'Presse latérale', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Fentes croisées', description: 'Fentes avec croisement des jambes', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Presse à cuisses inclinée', description: 'Presse avec dossier incliné', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Squat', description: 'Flexion des jambes classique', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Leg extension', description: 'Extension du genou sur machine', groupe: 'Quadriceps', categorie: 'guidee' },
    { nom: 'Montées sur banc', description: 'Step-up avec ou sans poids', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre', description: 'Deadlift classique', groupe: 'Quadriceps, Fessiers, Ischio-jambiers, Dos', categorie: 'libre' },
    { nom: 'Squat barre devant', description: 'Front squat', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Air Squat', description: 'Squat sans poids', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat sumo', description: 'Squat avec stance écartée', groupe: 'Quadriceps, Fessiers, Adducteurs', categorie: 'libre' },
    { nom: 'Squat sumo à la landmine', description: 'Squat sumo avec fixation pour barre', groupe: 'Quadriceps, Fessiers, Adducteurs', categorie: 'libre' },
    { nom: 'Hack squat', description: 'Squat avec barre derrière les jambes', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Overhead squat avec élastique', description: 'Squat avec bras tendus au-dessus', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'fonctionnel' },
    { nom: 'Sissy squat avec machine', description: 'Squat avancé sur machine', groupe: 'Quadriceps', categorie: 'guidee' },
    { nom: 'Pendulum squat', description: 'Squat sur machine pendulaire', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Belt squat', description: 'Squat avec poids attaché à une ceinture', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Pin squat', description: 'Squat avec arrêt sur pins', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Split squat avec élastique', description: 'Fente statique avec élastique', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Squat avec élastique', description: 'Squat avec résistance élastique', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Overhead squat avec haltères', description: 'Squat avec haltères tendus au-dessus', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'libre' },
    { nom: 'Squat avec bande de résistance', description: 'Squat avec bande élastique', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Montées sur banc latérales avec barre', description: 'Step-up latéral avec barre', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Croix de fer avec haltères', description: 'Squat avec bras en croix', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'libre' },
    { nom: 'Hack squat inversé', description: 'Variante inverse du hack squat', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Leg extension iso latéral unilatéral Hammer strength', description: 'Extension du genou unilatérale', groupe: 'Quadriceps', categorie: 'guidee' },
    { nom: 'Squat sur banc', description: 'Squat avec contact sur banc', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat goblet avec kettlebell', description: 'Squat avec kettlebell tenue devant', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Jefferson squat', description: 'Squat avec barre entre les jambes', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Zercher Squat', description: 'Squat avec barre dans le pli des coudes', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat statique contre un mur (exercice de la chaise)', description: 'Maintien en position squat', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Pistol squat', description: 'Squat sur une jambe', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Fentes avant avec kettlebell', description: 'Fentes avec kettlebell', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre sumo avec kettlebell', description: 'Deadlift sumo avec kettlebell', groupe: 'Quadriceps, Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Front squat avec haltères', description: 'Front squat avec haltères', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Sissy squat sans machine', description: 'Squat avancé sans support', groupe: 'Quadriceps', categorie: 'libre' },
    { nom: 'Presse à cuisses iso-latérale', description: 'Presse à cuisses unilatérale', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Squat sumo avec haltère', description: 'Squat avec stance large et haltère', groupe: 'Quadriceps, Fessiers, Adducteurs', categorie: 'libre' },
    { nom: 'Montées sur banc latérales avec haltères', description: 'Step-up latéral avec haltères', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Fentes avant avec barre', description: 'Fentes avec barre sur les épaules', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Split squat à la Smith machine', description: 'Fente statique guidée', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Thruster avec kettlebell', description: 'Squat et développé combinés', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'libre' },
    { nom: 'Squat avec sangles de suspension', description: 'Squat avec TRX', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Squat pistolet avec sangle de suspension', description: 'Pistol squat assisté', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Split squat avec sangles de suspension', description: 'Fente statique avec TRX', groupe: 'Quadriceps, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre valise', description: 'Deadlift avec charge sur un côté', groupe: 'Quadriceps, Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Soulevé de terre sumo', description: 'Deadlift avec stance écartée', groupe: 'Quadriceps, Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Thruster avec landmine', description: 'Squat et développé avec fixation pour barre', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'libre' },
    { nom: 'Soulevé de terre à la trap bar', description: 'Deadlift avec barre hexagonale', groupe: 'Quadriceps, Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Squat avant avec double kettlebell', description: 'Front squat avec deux kettlebells', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Safety bar squat', description: 'Squat avec barre spéciale', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Goblet squat avec haltère', description: 'Squat avec haltère tenue devant', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Fentes avant avec haltères', description: 'Fentes avec haltères', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Presse à cuisses horizontale', description: 'Presse à cuisses allongée', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Squat bulgare avec haltères', description: 'Fentes bulgares', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat à la Smith machine', description: 'Squat sur machine guidée', groupe: 'Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Fentes avec landmine', description: 'Fentes avec fixation pour barre', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat avec landmine', description: 'Squat avec fixation pour barre', groupe: 'Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat cossaque', description: 'Squat avec jambe tendue sur le côté', groupe: 'Quadriceps, Fessiers, Adducteurs', categorie: 'libre' },
    { nom: 'Extension de jambe unilatérale sur une machine à dips assistés', description: 'Extension du genou unilatérale', groupe: 'Quadriceps', categorie: 'guidee' },
    { nom: 'Overhead squat', description: 'Squat avec bras tendus au-dessus', groupe: 'Quadriceps, Fessiers, Épaules', categorie: 'libre' },
    { nom: 'Extension des jambes', description: 'Extension du genou', groupe: 'Quadriceps', categorie: 'guidee' },

    // Exercices des autres groupes musculaires mentionnés
    // Exercices pour les abdominaux (d'après les captures d'écran)
    { nom: 'Russian twist avec développé épaules', description: 'Rotation du buste avec poids', groupe: 'Abdominaux, Épaules', categorie: 'libre' },
    { nom: 'Planche', description: 'Gainage statique', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Crunch', description: 'Flexion du buste classique', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Sit-up décliné', description: 'Relevé de buste sur plan décliné', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Relevé de genoux suspendu', description: 'Relevé de genoux en suspension', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Relevé de jambes à la chaise romaine', description: 'Relevé de jambes sur support', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Roulette à abdominaux', description: 'Déroulé avec roulette', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Relevé de jambes suspendu', description: 'Élévation des jambes en suspension', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Crunch à la poulie', description: 'Crunch avec résistance constante', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Flexions des obliques au banc à lombaire à 45°', description: 'Flexion latérale sur banc incliné', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Planche latérale', description: 'Gainage sur le côté', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Mountain climber', description: 'Montées de genoux alternées en position de planche', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Rotations du buste avec barre', description: 'Rotations avec résistance', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Crunch sur swiss ball', description: 'Crunch sur ballon de gym', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Rotations des abdominaux suspendu', description: 'Rotations en position suspendue', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Sit-up avec médecine ball contre un mur', description: 'Sit-up avec lancer de ballon', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Crunch à la machine', description: 'Crunch sur machine guidée', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Dragon flag', description: 'Relevé du corps en position inverse', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Rotations latérales avec haltère', description: 'Rotations avec poids', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'AB Coaster', description: 'Exercice sur machine spécifique', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Crunch debout avec élastique', description: 'Crunch en position debout', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Crunch à la poulie pour les obliques', description: 'Crunch latéral à la poulie', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Crunch papillon', description: 'Crunch avec jambes en position papillon', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Crunch bicyclette', description: 'Crunch avec mouvement de pédalage', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Jackknife sur swiss ball', description: 'Fermeture du corps avec ballon', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Crunch avec sangles de suspension', description: 'Crunch avec TRX', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Rotations russes', description: 'Rotations du buste en position assise', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Cocon', description: 'Mouvement simultané des bras et des jambes', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Hollow hold', description: 'Position statique creusée', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Planche de l\'ours', description: 'Gainage sur mains et pieds', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Windmill', description: 'Mouvement de moulin avec le corps', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Planche sur Swiss ball', description: 'Gainage sur ballon', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Rotations du buste avec landmine', description: 'Rotations avec fixation pour barre', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Rotation du buste debout à la poulie', description: 'Rotation en position debout', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Flexions latérales à la poulie basse', description: 'Flexion latérale avec poulie', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Touche talon alternée', description: 'Touche de talons en position allongée', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Sits-up à la chaise romaine', description: 'Relevé de buste sur machine', groupe: 'Abdominaux', categorie: 'guidee' },
    { nom: 'Planche inversée', description: 'Gainage face au ciel', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Russian twists à la poulie sur Swiss ball', description: 'Rotations sur ballon avec poulie', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Relevé de jambes assis', description: 'Relevé des jambes en position assise', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Ciseaux', description: 'Mouvement des jambes en ciseaux', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Dead bug', description: 'Mouvement opposé bras/jambes', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Cercles jambes tendues', description: 'Mouvement circulaire des jambes', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Bear plank avec kickback', description: 'Planche avec extension de jambe', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Planche avec sangles de suspension', description: 'Gainage avec TRX', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Planche latérale avec rotation', description: 'Planche avec mouvement de rotation', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Crunch avec jambes verticales', description: 'Crunch jambes levées', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Rotation du buste avec élastique', description: 'Rotations avec résistance élastique', groupe: 'Abdominaux', categorie: 'fonctionnel' },
    { nom: 'Roulage avec une barre', description: 'Roulement du corps avec barre', groupe: 'Abdominaux', categorie: 'libre' },
    { nom: 'Zercher carry', description: 'Marche avec charge en position Zercher', groupe: 'Abdominaux, Corps complet', categorie: 'libre' },
    { nom: 'Extension des jambes', description: 'Extension du genou', groupe: 'Quadriceps', categorie: 'guidee' },
    // Exercices pour les ischio-jambiers (d'après les captures d'écran)
    { nom: 'Soulevé de terre jambes tendues', description: 'Deadlift avec jambes tendues', groupe: 'Ischio-jambiers', categorie: 'libre' },
    { nom: 'Leg curl allongé', description: 'Flexion du genou en position allongée', groupe: 'Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Presse à cuisses inclinée', description: 'Presse avec dossier incliné', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Squat', description: 'Flexion des jambes classique', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Good morning', description: 'Flexion du buste jambes tendues', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre roumain à la landmine', description: 'RDL avec fixation pour barre', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Rock Pull', description: 'Variante de deadlift', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Good morning avec élastique', description: 'Good morning avec résistance élastique', groupe: 'Ischio-jambiers, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre', description: 'Deadlift classique', groupe: 'Ischio-jambiers, Quadriceps, Fessiers, Dos', categorie: 'libre' },
    { nom: 'Kettlebell swing', description: 'Balancier avec kettlebell', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre roumain avec kettlebell', description: 'RDL avec kettlebell', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Presse à cuisses verticale', description: 'Presse à cuisses en position verticale', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'guidee' },
    { nom: 'Squat sumo à la landmine', description: 'Squat sumo avec fixation pour barre', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Leg curl au ballon de gym', description: 'Flexion du genou avec swiss ball', groupe: 'Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Leg curl unilatéral debout à la machine', description: 'Flexion du genou unilatérale', groupe: 'Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Reeves deadlift', description: 'Soulevé de terre avec prise par les disques', groupe: 'Ischio-jambiers, Dos', categorie: 'libre' },
    { nom: 'Leg curl décliné avec haltère', description: 'Flexion du genou avec haltère', groupe: 'Ischio-jambiers', categorie: 'libre' },
    { nom: 'Nordic hamstring curl avec élastique', description: 'Extension du genou avec résistance', groupe: 'Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre avec déficit', description: 'Deadlift sur plateforme', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Extension lombaire au banc à 45°', description: 'Extension du dos sur banc incliné', groupe: 'Ischio-jambiers, Lombaires', categorie: 'libre' },
    { nom: 'Soulevé de terre avec élastique', description: 'Deadlift avec résistance additionnelle', groupe: 'Ischio-jambiers, Fessiers', categorie: 'fonctionnel' },
    { nom: 'Squat goblet avec kettlebell', description: 'Squat avec kettlebell tenue devant', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Pistol squat', description: 'Squat sur une jambe', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Fentes avant avec kettlebell', description: 'Fentes avec kettlebell', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre sumo avec kettlebell', description: 'Deadlift sumo avec kettlebell', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Extensions de hanches au GHD', description: 'Extension sur machine spécifique', groupe: 'Ischio-jambiers, Fessiers', categorie: 'guidee' },
    { nom: 'Front squat avec haltères', description: 'Front squat avec haltères', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Squat sumo avec haltère', description: 'Squat avec stance large et haltère', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Fentes avant avec barre', description: 'Fentes avec barre sur les épaules', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre avec machine', description: 'Deadlift guidé', groupe: 'Ischio-jambiers, Fessiers', categorie: 'guidee' },
    { nom: 'Leg curl avec sangles de suspension', description: 'Flexion du genou avec TRX', groupe: 'Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre sumo', description: 'Deadlift avec stance large', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Soulevé de terre à la trap bar', description: 'Deadlift avec barre hexagonale', groupe: 'Ischio-jambiers, Quadriceps, Fessiers', categorie: 'libre' },
    { nom: 'Leg curl assis à la machine', description: 'Flexion du genou en position assise', groupe: 'Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Leg curl inversé sur le tirage vertical', description: 'Flexion du genou inversée', groupe: 'Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Zercher deadlift', description: 'Soulevé de terre avec barre dans les coudes', groupe: 'Ischio-jambiers, Fessiers', categorie: 'libre' },
    { nom: 'Leg curl allongé avec élastique', description: 'Flexion du genou avec élastique', groupe: 'Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Curl des jambes', description: 'Flexion du genou', groupe: 'Ischio-jambiers', categorie: 'guidee' },
    // Exercices pour les fessiers et ischio-jambiers (d'après les captures d'écran)
    { nom: 'Hack squat assis', description: 'Squat sur machine en position assise', groupe: 'Fessiers, Quadriceps', categorie: 'guidee' },
    { nom: 'Presse à cuisse sur le côté', description: 'Presse latérale', groupe: 'Fessiers', categorie: 'guidee' },
    { nom: 'Fentes croisées', description: 'Fentes avec croisement des jambes', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Hip thrust à la machine', description: 'Hip thrust guidé', groupe: 'Fessiers', categorie: 'guidee' },
    { nom: 'Squat', description: 'Flexion des jambes classique', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Soulevé de terre roumain', description: 'Deadlift jambes tendues', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Good morning', description: 'Flexion du buste avec barre', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Pull through à la poulie', description: 'Mouvement d\'extension des hanches', groupe: 'Fessiers', categorie: 'guidee' },
    { nom: 'Montées sur banc', description: 'Step-up avec ou sans poids', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Extension de la hanche à la poulie basse', description: 'Extension arrière à la poulie', groupe: 'Fessiers', categorie: 'guidee' },
    { nom: 'Hyperextension inversée au Swiss ball', description: 'Extension sur ballon', groupe: 'Fessiers, Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Reverse hyperextension', description: 'Extension inverse des hanches', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Soulevé de terre roumain à la landmine', description: 'Deadlift avec fixation pour barre', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Donkey kick', description: 'Coup de pied arrière', groupe: 'Fessiers', categorie: 'libre' },
    { nom: 'Fire hydrant', description: 'Abduction latérale de la jambe', groupe: 'Fessiers', categorie: 'libre' },
    { nom: 'Rack Pull', description: 'Soulevé de terre partiel', groupe: 'Fessiers, Dos', categorie: 'libre' },
    { nom: 'Good morning avec élastique', description: 'Good morning avec résistance élastique', groupe: 'Fessiers, Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Soulevé de terre', description: 'Deadlift classique', groupe: 'Fessiers, Ischio-jambiers, Dos', categorie: 'libre' },
    { nom: 'Kettlebell swing', description: 'Balancier avec kettlebell', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Squat barre devant', description: 'Front squat', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Soulevé de terre roumain avec kettlebell', description: 'RDL avec kettlebell', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Hip thrust unilatéral', description: 'Hip thrust à une jambe', groupe: 'Fessiers', categorie: 'libre' },
    { nom: 'Presse à cuisses verticale', description: 'Presse à cuisses en position verticale', groupe: 'Fessiers, Quadriceps', categorie: 'guidee' },
    { nom: 'Squat sumo', description: 'Squat avec stance écartée', groupe: 'Fessiers, Quadriceps, Adducteurs', categorie: 'libre' },
    { nom: 'Squat sumo à la landmine', description: 'Squat sumo avec fixation pour barre', groupe: 'Fessiers, Quadriceps, Adducteurs', categorie: 'libre' },
    { nom: 'Hack squat', description: 'Squat avec barre derrière les jambes', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Hip thrust à la smith machine', description: 'Hip thrust sur machine guidée', groupe: 'Fessiers', categorie: 'guidee' },
    { nom: 'Pin squat', description: 'Squat avec arrêt sur pins', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Bird dog', description: 'Extension bras/jambe opposés', groupe: 'Fessiers, Abdominaux', categorie: 'libre' },
    { nom: 'Hip thrusts à genoux avec élastique', description: 'Hip thrust en position agenouillée', groupe: 'Fessiers', categorie: 'fonctionnel' },
    { nom: 'Hip thrust', description: 'Élévation du bassin', groupe: 'Fessiers', categorie: 'libre' },
    { nom: 'Planche inversée', description: 'Gainage face vers le haut', groupe: 'Fessiers, Abdominaux', categorie: 'libre' },
    { nom: 'Pull through avec élastique', description: 'Pull through avec résistance élastique', groupe: 'Fessiers', categorie: 'fonctionnel' },
    { nom: 'Extension lombaire au banc à 45°', description: 'Extension du dos sur banc', groupe: 'Fessiers, Lombaires', categorie: 'libre' },
    { nom: 'Soulevé de terre avec élastique', description: 'Deadlift avec résistance additionnelle', groupe: 'Fessiers, Ischio-jambiers', categorie: 'fonctionnel' },
    { nom: 'Montées sur banc latérales avec barre', description: 'Step-up latéral avec barre', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Marche avec élastique', description: 'Marche avec résistance élastique', groupe: 'Fessiers, Quadriceps', categorie: 'fonctionnel' },
    { nom: 'Hack squat inversé', description: 'Variante inverse du hack squat', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Squat goblet avec kettlebell', description: 'Squat avec kettlebell tenue devant', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Zercher Squat', description: 'Squat avec barre dans le pli des coudes', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Pistol squat', description: 'Squat sur une jambe', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Fentes avant avec kettlebell', description: 'Fentes avec kettlebell', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Soulevé de terre sumo avec kettlebell', description: 'Deadlift sumo avec kettlebell', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Extensions de hanches au GHD', description: 'Extension sur machine spécifique', groupe: 'Fessiers, Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Front squat avec haltères', description: 'Front squat avec haltères', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Squat sumo avec haltère', description: 'Squat avec stance large et haltère', groupe: 'Fessiers, Quadriceps, Adducteurs', categorie: 'libre' },
    { nom: 'Montées sur banc latérales avec haltères', description: 'Step-up latéral avec haltères', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Fentes avant avec barre', description: 'Fentes avec barre sur les épaules', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Thruster avec kettlebell', description: 'Squat et développé combinés', groupe: 'Fessiers, Quadriceps, Épaules', categorie: 'libre' },
    { nom: 'Soulevé de terre avec machine', description: 'Deadlift guidé', groupe: 'Fessiers, Ischio-jambiers', categorie: 'guidee' },
    { nom: 'Bear plank avec kickback', description: 'Planche avec extension jambe', groupe: 'Fessiers, Abdominaux', categorie: 'libre' },
    { nom: 'Squat avec sangles de suspension', description: 'Squat avec TRX', groupe: 'Fessiers, Quadriceps', categorie: 'fonctionnel' },
    { nom: 'Hip thrust avec sangles de suspension', description: 'Hip thrust avec TRX', groupe: 'Fessiers', categorie: 'fonctionnel' },
    { nom: 'Goblet squat avec haltère', description: 'Squat avec haltère tenue devant', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Fentes avant avec haltères', description: 'Fentes avec haltères', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Presse à cuisses horizontale', description: 'Presse à cuisses allongée', groupe: 'Fessiers, Quadriceps', categorie: 'guidee' },
    { nom: 'Squat bulgare avec haltères', description: 'Fentes bulgares', groupe: 'Fessiers, Quadriceps', categorie: 'libre' },
    { nom: 'Zercher deadlift', description: 'Soulevé de terre Zercher', groupe: 'Fessiers, Ischio-jambiers', categorie: 'libre' },
    { nom: 'Thruster', description: 'Squat et développé combinés avec barre', groupe: 'Fessiers, Quadriceps, Épaules', categorie: 'libre' },
    // Exercices pour les mollets (d'après les captures d'écran)
    { nom: 'Extensions des mollets avec partenaire', description: 'Élévation des talons avec aide', groupe: 'Mollets', categorie: 'libre' },
    { nom: 'Extension des mollets à la barre debout', description: 'Élévation des talons avec barre', groupe: 'Mollets', categorie: 'libre' },
    { nom: 'Extensions des mollets assis avec barre', description: 'Élévation des talons avec barre en position assise', groupe: 'Mollets', categorie: 'libre' },
    { nom: 'Élévations des mollets au Donkey', description: 'Élévation des talons en position penchée', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extensions des mollets au hack-squat', description: 'Élévation des talons sur machine hack squat', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extensions des mollets assis à la Smith machine', description: 'Élévation des talons à la Smith machine', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extensions des mollets debout à la Smith machine', description: 'Élévation des talons debout à la Smith machine', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extensions des mollets debout à la machine', description: 'Élévation des talons sur machine spécifique', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extensions des mollets sur une marche', description: 'Élévation des talons sur marche ou step', groupe: 'Mollets', categorie: 'libre' },
    { nom: 'Extension des mollets assis à la machine', description: 'Élévation des talons sur machine assise', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Extension des mollets à la presse', description: 'Élévation des talons sur presse à cuisses', groupe: 'Mollets', categorie: 'guidee' },
    { nom: 'Élévations des mollets à la machine', description: 'Élévation des talons sur machine mollets', groupe: 'Mollets', categorie: 'guidee' },
];

async function main() {
  console.log(`Début de l'initialisation de la base de données...`);

  // Nettoyer les tables existantes
  await prisma.workout.deleteMany();
  await prisma.machine.deleteMany();
  
  console.log('Tables nettoyées. Ajout des machines par défaut...');

  // Ajouter les machines par défaut
  for (const machine of defaultMachines) {
    await prisma.machine.create({
      data: machine
    });
  }

  console.log(`${defaultMachines.length} machines ajoutées avec succès!`);
}

main()
  .catch((e) => {
    console.error('Erreur pendant l\'initialisation:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });